sudo: required
services:
  - docker

before_install:
  - docker build -t erickmauricio/docker-react -f Dockerfile.dev .

script:
  - docker run erickmauricio/docker-react npm run test -- -- coverage  